require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AramisEntitiesController do

  # This should return the minimal set of attributes required to create a valid
  # AramisEntity. As you add validations to AramisEntity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AramisEntitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all aramis_entities as @aramis_entities" do
      aramis_entity = AramisEntity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:aramis_entities).should eq([aramis_entity])
    end
  end

  describe "GET show" do
    it "assigns the requested aramis_entity as @aramis_entity" do
      aramis_entity = AramisEntity.create! valid_attributes
      get :show, {:id => aramis_entity.to_param}, valid_session
      assigns(:aramis_entity).should eq(aramis_entity)
    end
  end

  describe "GET new" do
    it "assigns a new aramis_entity as @aramis_entity" do
      get :new, {}, valid_session
      assigns(:aramis_entity).should be_a_new(AramisEntity)
    end
  end

  describe "GET edit" do
    it "assigns the requested aramis_entity as @aramis_entity" do
      aramis_entity = AramisEntity.create! valid_attributes
      get :edit, {:id => aramis_entity.to_param}, valid_session
      assigns(:aramis_entity).should eq(aramis_entity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AramisEntity" do
        expect {
          post :create, {:aramis_entity => valid_attributes}, valid_session
        }.to change(AramisEntity, :count).by(1)
      end

      it "assigns a newly created aramis_entity as @aramis_entity" do
        post :create, {:aramis_entity => valid_attributes}, valid_session
        assigns(:aramis_entity).should be_a(AramisEntity)
        assigns(:aramis_entity).should be_persisted
      end

      it "redirects to the created aramis_entity" do
        post :create, {:aramis_entity => valid_attributes}, valid_session
        response.should redirect_to(AramisEntity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved aramis_entity as @aramis_entity" do
        # Trigger the behavior that occurs when invalid params are submitted
        AramisEntity.any_instance.stub(:save).and_return(false)
        post :create, {:aramis_entity => { "name" => "invalid value" }}, valid_session
        assigns(:aramis_entity).should be_a_new(AramisEntity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AramisEntity.any_instance.stub(:save).and_return(false)
        post :create, {:aramis_entity => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested aramis_entity" do
        aramis_entity = AramisEntity.create! valid_attributes
        # Assuming there are no other aramis_entities in the database, this
        # specifies that the AramisEntity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AramisEntity.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => aramis_entity.to_param, :aramis_entity => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested aramis_entity as @aramis_entity" do
        aramis_entity = AramisEntity.create! valid_attributes
        put :update, {:id => aramis_entity.to_param, :aramis_entity => valid_attributes}, valid_session
        assigns(:aramis_entity).should eq(aramis_entity)
      end

      it "redirects to the aramis_entity" do
        aramis_entity = AramisEntity.create! valid_attributes
        put :update, {:id => aramis_entity.to_param, :aramis_entity => valid_attributes}, valid_session
        response.should redirect_to(aramis_entity)
      end
    end

    describe "with invalid params" do
      it "assigns the aramis_entity as @aramis_entity" do
        aramis_entity = AramisEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AramisEntity.any_instance.stub(:save).and_return(false)
        put :update, {:id => aramis_entity.to_param, :aramis_entity => { "name" => "invalid value" }}, valid_session
        assigns(:aramis_entity).should eq(aramis_entity)
      end

      it "re-renders the 'edit' template" do
        aramis_entity = AramisEntity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AramisEntity.any_instance.stub(:save).and_return(false)
        put :update, {:id => aramis_entity.to_param, :aramis_entity => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested aramis_entity" do
      aramis_entity = AramisEntity.create! valid_attributes
      expect {
        delete :destroy, {:id => aramis_entity.to_param}, valid_session
      }.to change(AramisEntity, :count).by(-1)
    end

    it "redirects to the aramis_entities list" do
      aramis_entity = AramisEntity.create! valid_attributes
      delete :destroy, {:id => aramis_entity.to_param}, valid_session
      response.should redirect_to(aramis_entities_url)
    end
  end

end
